# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      sudo apt update
      sudo apt upgrade -y
      sudo apt install postgresql postgresql-contrib -y
      pip install django
      pg_ctl start
      cd WebSubject && python manage.py makemigrations && python manage.py migrate
    command: |
      pg_ctl start
      cd WebSubject && manage.py runserver

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - esbenp.prettier-vscode
    - ms-python.python
    - VisualStudioExptTeam.vscodeintellicode
    - dbaeumer.vscode-eslint
    - formulahendry.auto-rename-tag
    - kevinkyang.auto-comment-blocks
    - adpyke.codesnap
