# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      sudo apt update
      sudo apt install postgresql postgresql-contrib
      pip install django
      cd WebSubject && python manage.py makemigrations && python manage.py migrate
    command: |
      pg_ctl start
      manage.py runserver


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
