# Generated by Django 3.2.5 on 2022-07-15 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='t_id',
            new_name='p_id',
        ),
    ]
