# Generated by Django 4.0.4 on 2022-05-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=16, verbose_name='帖子id')),
                ('t_uid', models.CharField(max_length=16, verbose_name='帖子所属用户id')),
                ('t_kind', models.CharField(max_length=32, verbose_name='类别')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('t_content', models.CharField(max_length=3000, verbose_name='帖子正文')),
                ('t_title', models.CharField(max_length=64, verbose_name='帖子标题')),
                ('t_introduce', models.CharField(max_length=256, verbose_name='帖子简介')),
                ('recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
            ],
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='r_photo',
        ),
    ]
