# Generated by Django 4.0.4 on 2022-05-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_content_delete_topic_remove_reply_r_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='t_id',
            field=models.CharField(max_length=16, verbose_name='指向内容的id'),
        ),
    ]
