# Generated by Django 4.0.4 on 2022-05-24 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0003_alter_content_t_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='recommend',
        ),
        migrations.RemoveField(
            model_name='content',
            name='t_uid',
        ),
        migrations.AddField(
            model_name='content',
            name='t_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
