# Generated by Django 4.0.4 on 2022-05-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_content_recommend_remove_content_t_uid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='t_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='t_introduce',
            new_name='intro',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='t_kind',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='t_title',
            new_name='title',
        ),
    ]
