# Generated by Django 4.0.4 on 2022-05-25 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_content_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='content',
            name='t_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.content', verbose_name='指向内容的id'),
        ),
    ]
