# Generated by Django 3.2.5 on 2022-05-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_rename_content_content_text_alter_content_t_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='b_id',
            new_name='book',
        ),
    ]
