# Generated by Django 3.2.5 on 2022-05-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_rename_b_id_index_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='t_user',
            new_name='author',
        ),
    ]
