# Generated by Django 3.2.5 on 2022-07-12 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interface', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='书名')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='封面')),
                ('language', models.CharField(max_length=50, verbose_name='语言')),
                ('intro', models.TextField(verbose_name='简介')),
                ('latest_c_num', models.IntegerField(default=0, verbose_name='最新章节号')),
                ('if_pub', models.BooleanField(verbose_name='是否出版')),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Starts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars1', models.BigIntegerField(verbose_name='一星评价')),
                ('stars2', models.BigIntegerField(verbose_name='二星评价')),
                ('stars3', models.BigIntegerField(verbose_name='三星评价')),
                ('stars4', models.BigIntegerField(verbose_name='四星评价')),
                ('stars5', models.BigIntegerField(verbose_name='五星评价')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='所评分的书籍')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='系列名称')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='封面')),
                ('language', models.CharField(max_length=50, verbose_name='语言')),
                ('text', models.TextField(verbose_name='简介')),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='分节信息')),
            ],
        ),
        migrations.CreateModel(
            name='Pubinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=15, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=20, verbose_name='出版社')),
                ('seller', models.CharField(blank=True, max_length=20, verbose_name='出品方')),
                ('otitle', models.CharField(blank=True, max_length=20, verbose_name='原作名')),
                ('puear', models.CharField(blank=True, max_length=20, verbose_name='出版年')),
                ('pnum', models.CharField(blank=True, max_length=20, verbose_name='页数')),
                ('Price', models.CharField(blank=True, max_length=20, verbose_name='定价')),
                ('fram', models.CharField(blank=True, max_length=20, verbose_name='装帧')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='书籍ID')),
                ('translator', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='译者')),
            ],
        ),
        migrations.CreateModel(
            name='Gsentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='书籍ID')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='章节号')),
                ('title', models.CharField(max_length=50, verbose_name='章节名')),
                ('content', models.TextField(verbose_name='内容')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='书籍ID')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.series', verbose_name='系列'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='interface.Tag', verbose_name='标签'),
        ),
    ]
