# Generated by Django 4.0.4 on 2022-05-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='书名')),
                ('cover', models.ImageField(upload_to='cover/', verbose_name='封面')),
                ('language', models.CharField(max_length=50, verbose_name='语言')),
                ('intro', models.TextField(verbose_name='简介')),
                ('if_pub', models.IntegerField(verbose_name='是否出版')),
                ('author', models.ManyToManyField(to='users.user', verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='系列名称')),
                ('cover', models.ImageField(upload_to='cover/', verbose_name='封面')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('language', models.CharField(max_length=50, verbose_name='语言')),
                ('intro', models.TextField(verbose_name='简介')),
            ],
        ),
        migrations.CreateModel(
            name='Starts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars1', models.BigIntegerField(verbose_name='一星评价')),
                ('stars2', models.BigIntegerField(verbose_name='二星评价')),
                ('stars3', models.BigIntegerField(verbose_name='三星评价')),
                ('stars4', models.BigIntegerField(verbose_name='四星评价')),
                ('stars5', models.BigIntegerField(verbose_name='五星评价')),
            ],
        ),
        migrations.CreateModel(
            name='Pubinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=15, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=20, verbose_name='出版社')),
                ('seller', models.CharField(blank=True, max_length=20, verbose_name='出品方')),
                ('otitle', models.CharField(blank=True, max_length=20, verbose_name='原作名')),
                ('translator', models.CharField(blank=True, max_length=20, verbose_name='译者')),
                ('puear', models.CharField(blank=True, max_length=20, verbose_name='出版年')),
                ('pnum', models.CharField(blank=True, max_length=20, verbose_name='页数')),
                ('Price', models.CharField(blank=True, max_length=20, verbose_name='定价')),
                ('fram', models.CharField(blank=True, max_length=20, verbose_name='装帧')),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='书籍ID')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='章节号')),
                ('title', models.CharField(max_length=50, verbose_name='章节名')),
                ('content', models.TextField(verbose_name='内容')),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='书籍ID')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.series', verbose_name='系列'),
        ),
        migrations.AddField(
            model_name='book',
            name='starts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.starts', verbose_name='评分'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='tags.tag', verbose_name='标签'),
        ),
    ]
