# Generated by Django 3.2.5 on 2022-07-24 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='书名')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='封面')),
                ('language', models.CharField(max_length=50, verbose_name='语言')),
                ('intro', models.TextField(verbose_name='简介')),
                ('latest_c_num', models.IntegerField(default=0, verbose_name='最新章节号')),
                ('if_pub', models.BooleanField(verbose_name='是否出版')),
                ('Related_Information', models.TextField(blank=True, null=True, verbose_name='相关信息')),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Starts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars0', models.BigIntegerField(default=0, verbose_name='零星评价')),
                ('stars1', models.BigIntegerField(default=0, verbose_name='一星评价')),
                ('stars2', models.BigIntegerField(default=0, verbose_name='二星评价')),
                ('stars3', models.BigIntegerField(default=0, verbose_name='三星评价')),
                ('stars4', models.BigIntegerField(default=0, verbose_name='四星评价')),
                ('stars5', models.BigIntegerField(default=0, verbose_name='五星评价')),
                ('stars6', models.BigIntegerField(default=0, verbose_name='六星评价')),
                ('stars7', models.BigIntegerField(default=0, verbose_name='七星评价')),
                ('stars8', models.BigIntegerField(default=0, verbose_name='八星评价')),
                ('stars9', models.BigIntegerField(default=0, verbose_name='九星评价')),
                ('stars10', models.BigIntegerField(default=0, verbose_name='十星评价')),
                ('b_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='所评分的书籍')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='系列名称')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='封面')),
                ('language', models.CharField(max_length=50, verbose_name='语言')),
                ('text', models.TextField(verbose_name='简介')),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='分节信息')),
            ],
        ),
        migrations.CreateModel(
            name='Pubinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=15, verbose_name='ISBN')),
                ('content', models.TextField(verbose_name='内容')),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='书籍ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gsentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='书籍ID')),
                ('p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.gsentence', verbose_name='指向内容的id')),
                ('u_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='书籍ID')),
                ('p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.comment', verbose_name='指向内容的id')),
                ('u_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='章节号')),
                ('title', models.CharField(max_length=50, verbose_name='章节名')),
                ('content', models.TextField(verbose_name='内容')),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='书籍ID')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.series', verbose_name='系列'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='interface.Tag', verbose_name='标签'),
        ),
    ]
