# Generated by Django 3.2.5 on 2022-07-20 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='book',
            new_name='b_id',
        ),
        migrations.RenameField(
            model_name='gsentence',
            old_name='book',
            new_name='b_id',
        ),
        migrations.RenameField(
            model_name='pubinfo',
            old_name='book',
            new_name='b_id',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='book',
            new_name='b_id',
        ),
        migrations.RemoveField(
            model_name='pubinfo',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='pubinfo',
            name='fram',
        ),
        migrations.RemoveField(
            model_name='pubinfo',
            name='otitle',
        ),
        migrations.RemoveField(
            model_name='pubinfo',
            name='pnum',
        ),
        migrations.RemoveField(
            model_name='pubinfo',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='pubinfo',
            name='puear',
        ),
        migrations.RemoveField(
            model_name='pubinfo',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='pubinfo',
            name='translator',
        ),
        migrations.AddField(
            model_name='pubinfo',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='内容'),
            preserve_default=False,
        ),
    ]
