# Generated by Django 3.2.5 on 2022-08-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='b_id',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='number',
        ),
        migrations.AddField(
            model_name='section',
            name='deep',
            field=models.IntegerField(default=0, verbose_name='深度'),
        ),
        migrations.AddField(
            model_name='section',
            name='number',
            field=models.IntegerField(default=0, verbose_name='章节号'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.URLField(blank=True, null=True, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover',
            field=models.URLField(blank=True, null=True, verbose_name='封面'),
        ),
    ]
