# Generated by Django 4.0.4 on 2022-05-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_text_tag_title_alter_tag_tid'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='if_pub',
            field=models.BooleanField(verbose_name='是否出版'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(default='books', to='tags.tag', verbose_name='标签'),
        ),
    ]
