# Generated by Django 3.2.5 on 2022-08-21 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220820_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='c_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.chapter', verbose_name='对应章节'),
            preserve_default=False,
        ),
    ]
