# Generated by Django 4.0.4 on 2022-05-11 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_text_tag_title_alter_tag_tid'),
        ('books', '0002_alter_book_if_pub_alter_book_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='intro',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='book',
            name='starts',
        ),
        migrations.AddField(
            model_name='starts',
            name='book',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='评分'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='tags.tag', verbose_name='标签'),
        ),
    ]
