# Generated by Django 3.2.5 on 2022-07-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220720_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starts',
            old_name='book',
            new_name='b_id',
        ),
    ]
