# Generated by Django 3.2.5 on 2022-05-15 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_rename_intro_series_text_remove_book_starts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='series',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.RemoveField(
            model_name='pubinfo',
            name='translator',
        ),
        migrations.AddField(
            model_name='pubinfo',
            name='translator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='译者'),
        ),
        migrations.RemoveField(
            model_name='series',
            name='author',
        ),
        migrations.AddField(
            model_name='series',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='series',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='starts',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='所评分的书籍'),
        ),
    ]
