# Generated by Django 3.2.5 on 2022-05-15 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20220515_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.series', verbose_name='系列'),
        ),
    ]
