# Generated by Django 4.0.4 on 2022-05-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='latest_c_num',
            field=models.IntegerField(default=0, verbose_name='最新章节号'),
            preserve_default=False,
        ),
    ]
