# Generated by Django 3.2.5 on 2022-07-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20220720_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='starts',
            name='stars0',
            field=models.BigIntegerField(default=0, verbose_name='零星评价'),
        ),
        migrations.AddField(
            model_name='starts',
            name='stars10',
            field=models.BigIntegerField(default=0, verbose_name='十星评价'),
        ),
        migrations.AddField(
            model_name='starts',
            name='stars6',
            field=models.BigIntegerField(default=0, verbose_name='六星评价'),
        ),
        migrations.AddField(
            model_name='starts',
            name='stars7',
            field=models.BigIntegerField(default=0, verbose_name='七星评价'),
        ),
        migrations.AddField(
            model_name='starts',
            name='stars8',
            field=models.BigIntegerField(default=0, verbose_name='八星评价'),
        ),
        migrations.AddField(
            model_name='starts',
            name='stars9',
            field=models.BigIntegerField(default=0, verbose_name='九星评价'),
        ),
    ]
