# Generated by Django 4.0.4 on 2022-05-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_latest_c_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='latest_c_num',
            field=models.IntegerField(default=0, verbose_name='最新章节号'),
        ),
    ]
