# Generated by Django 3.2.5 on 2022-07-21 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_gsentence_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Related_Information',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='相关信息'),
            preserve_default=False,
        ),
    ]
