# Generated by Django 3.2.5 on 2022-07-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_related_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Related_Information',
            field=models.TextField(blank=True, null=True, verbose_name='相关信息'),
        ),
    ]
