# Generated by Django 3.2.5 on 2022-05-29 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_gsentence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='b_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='gsentence',
            old_name='b_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='pubinfo',
            old_name='b_id',
            new_name='book',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='分节信息')),
            ],
        ),
    ]
