# Generated by Django 4.0.4 on 2022-05-27 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0007_alter_book_latest_c_num'),
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='b_id',
        ),
        migrations.RemoveField(
            model_name='bookshelf',
            name='f_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='u_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='B_bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book', verbose_name='书籍ID')),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.bookshelf', verbose_name='指向书架的id')),
            ],
        ),
    ]
