# Generated by Django 3.2.5 on 2022-07-23 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_alter_status_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='integral',
            field=models.BigIntegerField(default=1, verbose_name='积分'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='Continuous_check_in_time',
            field=models.IntegerField(default=1992, verbose_name='连续签到时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='check_in_time',
            field=models.DateField(auto_now=True, verbose_name='最后签到日期'),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='status',
            name='u_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID'),
        ),
        migrations.CreateModel(
            name='TEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dddd', models.DateField(auto_now=True, verbose_name='最后签到日期')),
                ('u_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
        ),
    ]
