# Generated by Django 3.2.5 on 2022-05-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_b_bookshelf_bookforbs_alter_profile_u_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookforbs',
            old_name='b_id',
            new_name='book',
        ),
    ]
