# Generated by Django 4.0.4 on 2022-05-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='text',
            field=models.TextField(default=1, verbose_name='标签简介'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(default=2, max_length=40, verbose_name='标签名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='tid',
            field=models.CharField(max_length=90, verbose_name='标签识别名'),
        ),
    ]
